### ISSUE TITLE
Can't install on 11

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/files_downloadactivity#3]
@ popomoc in https://github.com/nextcloud/server/issues/853#issuecomment-272410266

> Hello,
> is possible to isnall the app in nextcloud 11 ? i tryed but there is an error message: 
> 
> This app has no minimum Nextcloud version assigned. This will be an error in the future.
> 
> This app cannot be installed because the following dependencies are not fulfilled:
> 
>     Server version 9.2 or lower is required.
> 
> If i try to change max version in xml also not helps me :(
> 
> Thank you
> BR
> tom

**Comment by nickvergessen** [comment]
@popomoc you can now install the app via the appstore:
https://apps.nextcloud.com/apps/files_downloadactivity

Might take some minutes until your instance invalidates the app list of the app store, but then it should be installable via a simple click in the app management.

**Comment by rapITler** [comment]
Hi,

I am still not able to install it. 

Still receive:
This app cannot be installed because the following dependencies are not fulfilled:
Server version 12 or higher is required.

Any suggestions?

Thank you!

**Comment by nickvergessen** [comment]
Please intall via the app store

**Comment by popomoc** [comment]
Hello, yes  it workig very great on v 11

**Comment by rapITler** [comment]
Oh ok it seems to me may I can't see the AppStore because my server have  restricted access to the web. I thought "installing from appstore" means download it manually from there. 

As I don't know how it should looks like may you can tell me which URL must be possible to access the Appstore directly from the next loud GUI. I am only able to see "enabled" and "not enabled".

Thx

**Comment by nickvergessen** [comment]
You can also download it manually from https://github.com/nextcloud/files_downloadactivity/releases
Otherwise allow requests to apps.nextcloud.com

**Comment by rapITler** [comment]
Hi,

@nickvergessen: Thank you - I previously installed it with gitclone which didn't work.
Anyway - i will allow requests to apps.nextcloud.com for further installations.

thx!

**Comment by popomoc** [comment]
Hello,  
  
isn t there any way to export download activity into PDF like file
transfer auditing?  
It wil bbe awesome.  
  
Is it possible to make it?  
  
Thank you  
br  
Dave  
  


> ** Thu, 02 Feb 2017 09:58:23 -0800 -
"nextcloud/files_downloadactivity" <reply+017efeb46f73c7c09334a9979946cc
e562a28a51f7cc24fa92cf0000000114ab353f92a169ce0bf4dc79@reply.github.com>
**  
  

>

> Oh ok it seems to me may I can't see the AppStore because my server
have restricted access to the web. I thought "installing from appstore"
means download it manually from there.

>

> As I don't know how it should looks like may you can tell me which URL
must be possible to access the Appstore directly from the next loud GUI.
I am only able to see "enabled" and "not enabled".

>

> Thx

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly, [view it on GitHub](https://github.com/nex
tcloud/files_downloadactivity/issues/3#issuecomment-277032744), or [mute
the thread](https://github.com/notifications/unsubscribe-
auth/AX7-tDQmNdcONMdAvaV9t82E4P5qzN2Nks5rYhk_gaJpZM4Liu85).

>

>
